### ISSUE TITLE
markdown-it and highlight.js as peerDependencies?

### ISSUE THREAD

**Issue by arve0** [unindented/markdown-it-loader#9]
With markdown-it and highlight.js as peer dependencies, one does not need to update markdown-it-loader when markdown-it and highlight.js updates. Also, it will allow for more flexible version control, if you want to stay on say markdown-it `^5.0.0`.

**Comment by unindented** [comment]
You are totally right. I'll fix it.

**Comment by unindented** [comment]
Fixed with https://github.com/unindented/markdown-it-loader/commit/8945ec84b5d823b16478d428c7d22fe996e4b2ca.
